[tool.isort]
profile = "black"
multi_line_output = 3 # Vertical Hanging Indent
line_length = 79
include_trailing_comma = "True"
length_sort = "False"
length_sort_sections = "stdlib"
known_first_party = "btrack"
known_napari = "napari"
sections = ["STDLIB", "THIRDPARTY", "NAPARI", "FIRSTPARTY", "LOCALFOLDER"]
skip_gitignore = "True"
